# Generated by Django 4.1.7 on 2023-06-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bank_id_branch_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank',
            new_name='bank_id',
        ),
    ]
